import type { Banner, Category, Customer, Order, Product } from "@/types/database.types";

/**
 * Dados de exemplo — usados enquanto o Supabase real não está configurado
 * (ver `src/lib/queries.ts`). Fotos: Unsplash, uso editorial/mock.
 */

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-bebe", slug: "bebe", name: "Bebê", parent_id: null, image_url: "https://images.unsplash.com/photo-1768693602418-260d828b878d?auto=format&fit=crop&w=400&q=80", position: 1 },
  { id: "cat-menina", slug: "menina", name: "Menina", parent_id: null, image_url: "https://images.unsplash.com/photo-1571240571053-3ddc83cdb289?auto=format&fit=crop&w=400&q=80", position: 2 },
  { id: "cat-menino", slug: "menino", name: "Menino", parent_id: null, image_url: "https://images.unsplash.com/photo-1596392927852-2a18c336fb78?auto=format&fit=crop&w=400&q=80", position: 3 },
  { id: "cat-calcados", slug: "calcados", name: "Calçados", parent_id: null, image_url: "https://images.unsplash.com/photo-1600455745764-ebd75e6cd567?auto=format&fit=crop&w=400&q=80", position: 4 },
  { id: "cat-acessorios", slug: "acessorios", name: "Acessórios", parent_id: null, image_url: "https://images.unsplash.com/photo-1636096428948-f59b59c42b0f?auto=format&fit=crop&w=400&q=80", position: 5 },
  { id: "cat-menina-vestidos", slug: "menina-vestidos", name: "Vestidos", parent_id: "cat-menina", image_url: null, position: 1 },
  { id: "cat-menino-conjuntos", slug: "menino-conjuntos", name: "Conjuntos", parent_id: "cat-menino", image_url: null, position: 1 },
];

let imgCounter = 0;
const img = (url: string, alt: string): Product["images"][number] => ({
  id: `img-${++imgCounter}`,
  product_id: "",
  url: `${url}?auto=format&fit=crop&w=1080&q=80`,
  alt,
  position: 1,
});

function sizes(values: string[], stockEach = 6): Product["variations"] {
  return values.map((value, i) => ({
    id: `var-${value}-${i}`,
    product_id: "",
    label: "Tamanho",
    value,
    stock: stockEach,
  }));
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p-01",
    slug: "vestido-jardim-encantado",
    name: "Vestido Jardim Encantado",
    description:
      "Vestido rodado em algodão leve, forro macio e bordado floral delicado. Perfeito para o dia a dia e para ocasiões especiais.",
    category_id: "cat-menina-vestidos",
    color: "Verde-menta",
    price_cents: 15900,
    compare_at_price_cents: 18900,
    stock: 24,
    weight_grams: 220,
    active: true,
    featured_section: "novidades",
    images: [img("https://images.unsplash.com/photo-1571240571053-3ddc83cdb289", "Vestido Jardim Encantado, verde-menta")],
    variations: sizes(["1", "2", "3", "4", "6"]),
  },
  {
    id: "p-02",
    slug: "vestido-domingo-em-familia",
    name: "Vestido Domingo em Família",
    description: "Vestido branco em piquet, gola redonda e laço rosa na cintura. Tecido que respira e não amassa fácil.",
    category_id: "cat-menina-vestidos",
    color: "Branco",
    price_cents: 16900,
    compare_at_price_cents: null,
    stock: 18,
    weight_grams: 210,
    active: true,
    featured_section: "mais-vendidos",
    images: [img("https://images.unsplash.com/photo-1578178107900-e8ef3855b9cf", "Vestido Domingo em Família, branco")],
    variations: sizes(["RN", "P", "M", "G", "1", "2"]),
  },
  {
    id: "p-03",
    slug: "vestido-tarde-de-verao",
    name: "Vestido Tarde de Verão",
    description: "Estampa exclusiva de estrelinhas, alcinhas ajustáveis e forro antitransparência.",
    category_id: "cat-menina-vestidos",
    color: "Amarelo",
    price_cents: 17900,
    compare_at_price_cents: 21900,
    stock: 12,
    weight_grams: 200,
    active: true,
    featured_section: "promocoes",
    images: [img("https://images.unsplash.com/photo-1759313560250-3bb4bc1d10bc", "Vestido Tarde de Verão, estampa de estrelas")],
    variations: sizes(["2", "3", "4", "6", "8"]),
  },
  {
    id: "p-04",
    slug: "vestido-piquenique-no-parque",
    name: "Vestido Piquenique no Parque",
    description: "Xadrez vichy azul-esverdeado, cós elástico confortável para brincar sem limites.",
    category_id: "cat-menina-vestidos",
    color: "Verde-água",
    price_cents: 14900,
    compare_at_price_cents: null,
    stock: 20,
    weight_grams: 190,
    active: true,
    featured_section: null,
    images: [img("https://images.unsplash.com/photo-1599624427857-461fd60c23e5", "Vestido Piquenique no Parque")],
    variations: sizes(["1", "2", "3", "4"]),
  },
  {
    id: "p-05",
    slug: "camisa-social-pequeno-cavalheiro",
    name: "Camisa Social Pequeno Cavalheiro",
    description: "Camisa em tricoline com colarinho reforçado — ideal para festas e cerimônias.",
    category_id: "cat-menino-conjuntos",
    color: "Azul-marinho",
    price_cents: 13900,
    compare_at_price_cents: null,
    stock: 22,
    weight_grams: 180,
    active: true,
    featured_section: "novidades",
    images: [img("https://images.unsplash.com/photo-1673340979193-481dd0eb49c8", "Camisa Social Pequeno Cavalheiro")],
    variations: sizes(["1", "2", "3", "4", "6", "8"]),
  },
  {
    id: "p-06",
    slug: "conjunto-explorador-fim-de-semana",
    name: "Conjunto Explorador Fim de Semana",
    description: "Camiseta + bermuda em moletom leve, com bolso funcional e acabamento reforçado nos joelhos.",
    category_id: "cat-menino-conjuntos",
    color: "Verde-oliva",
    price_cents: 12900,
    compare_at_price_cents: 15900,
    stock: 30,
    weight_grams: 260,
    active: true,
    featured_section: "mais-vendidos",
    images: [img("https://images.unsplash.com/photo-1596392927852-2a18c336fb78", "Conjunto Explorador Fim de Semana")],
    variations: sizes(["2", "3", "4", "6", "8", "10"]),
  },
  {
    id: "p-07",
    slug: "conjunto-passeio-no-parque",
    name: "Conjunto Passeio no Parque",
    description: "Blazer estruturado + calça em sarja, corte confortável para um visual elegante sem perder o conforto.",
    category_id: "cat-menino-conjuntos",
    color: "Bege",
    price_cents: 19900,
    compare_at_price_cents: null,
    stock: 14,
    weight_grams: 320,
    active: true,
    featured_section: null,
    images: [img("https://images.unsplash.com/photo-1681551210432-228395e59420", "Conjunto Passeio no Parque")],
    variations: sizes(["1", "2", "3", "4"]),
  },
  {
    id: "p-08",
    slug: "body-primeiros-passos",
    name: "Body Primeiros Passos (kit 3 peças)",
    description: "Kit com 3 bodies em algodão pima, costura plana que não irrita a pele do bebê.",
    category_id: "cat-bebe",
    color: "Rosa-algodão-doce",
    price_cents: 11900,
    compare_at_price_cents: null,
    stock: 40,
    weight_grams: 150,
    active: true,
    featured_section: "mais-vendidos",
    images: [img("https://images.unsplash.com/photo-1768693602418-260d828b878d", "Kit body Primeiros Passos")],
    variations: sizes(["RN", "P", "M", "G"], 10),
  },
  {
    id: "p-09",
    slug: "macacao-soneca-tranquila",
    name: "Macacão Soneca Tranquila",
    description: "Macacão de manga longa em plush ultra macio, zíper duplo para trocas rápidas.",
    category_id: "cat-bebe",
    color: "Verde-menta",
    price_cents: 13900,
    compare_at_price_cents: 16900,
    stock: 26,
    weight_grams: 210,
    active: true,
    featured_section: "promocoes",
    images: [img("https://images.unsplash.com/photo-1636096428948-f59b59c42b0f", "Macacão Soneca Tranquila")],
    variations: sizes(["RN", "P", "M"], 8),
  },
  {
    id: "p-10",
    slug: "tenis-primeiros-saltos",
    name: "Tênis Primeiros Saltos",
    description: "Solado antiderrapante e flexível, ideal para os primeiros passos com segurança.",
    category_id: "cat-calcados",
    color: "Branco/Rosa",
    price_cents: 15900,
    compare_at_price_cents: null,
    stock: 22,
    weight_grams: 260,
    active: true,
    featured_section: "novidades",
    images: [img("https://images.unsplash.com/photo-1600455745764-ebd75e6cd567", "Tênis Primeiros Saltos")],
    variations: sizes(["19", "20", "21", "22", "23"], 5),
  },
  {
    id: "p-11",
    slug: "tenis-recreio-livre",
    name: "Tênis Recreio Livre",
    description: "Cabedal respirável e velcro duplo — fácil de calçar sozinho, resistente para o pátio da escola.",
    category_id: "cat-calcados",
    color: "Verde/Branco",
    price_cents: 17900,
    compare_at_price_cents: 19900,
    stock: 16,
    weight_grams: 280,
    active: true,
    featured_section: "mais-vendidos",
    images: [img("https://images.unsplash.com/photo-1678192568478-9488ee55def6", "Tênis Recreio Livre")],
    variations: sizes(["24", "26", "28", "30", "32"], 6),
  },
  {
    id: "p-12",
    slug: "sandalia-tarde-de-sol",
    name: "Sandália Tarde de Sol",
    description: "Sandália em couro sintético com fivela ajustável e palmilha macia.",
    category_id: "cat-calcados",
    color: "Caramelo",
    price_cents: 9900,
    compare_at_price_cents: null,
    stock: 28,
    weight_grams: 150,
    active: true,
    featured_section: null,
    images: [img("https://images.unsplash.com/photo-1605317143724-025ceb00651c", "Sandália Tarde de Sol")],
    variations: sizes(["20", "22", "24", "26", "28"], 6),
  },
  {
    id: "p-13",
    slug: "laco-duplo-framboesa",
    name: "Laço Duplo Framboesa (par)",
    description: "Par de laços em fita de cetim, presilha jacaré emborrachada que não escorrega.",
    category_id: "cat-acessorios",
    color: "Rosa-framboesa",
    price_cents: 3900,
    compare_at_price_cents: null,
    stock: 60,
    weight_grams: 20,
    active: true,
    featured_section: "promocoes",
    images: [img("https://images.unsplash.com/photo-1542901689-f103b03b9e97", "Laço Duplo Framboesa")],
    variations: [],
  },
  {
    id: "p-14",
    slug: "mochila-pequena-aventureira",
    name: "Mochila Pequena Aventureira",
    description: "Mochila em lona resistente com alças acolchoadas e bolso frontal para os tesouros do dia.",
    category_id: "cat-acessorios",
    color: "Verde-menta",
    price_cents: 8900,
    compare_at_price_cents: null,
    stock: 34,
    weight_grams: 300,
    active: true,
    featured_section: "novidades",
    images: [img("https://images.unsplash.com/photo-1572187092690-63fffd19feb2", "Mochila Pequena Aventureira")],
    variations: [],
  },
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: "b-01",
    title: "Nova coleção chegou",
    subtitle: "Peças fresquinhas para os pequenos aproveitarem o sol",
    image_url: "https://images.unsplash.com/photo-1611003967145-fb3960072424?auto=format&fit=crop&w=1600&q=80",
    href: "/produtos?destaque=novidades",
    position: 1,
    active: true,
  },
  {
    id: "b-02",
    title: "Até 30% off em calçados",
    subtitle: "Enquanto durar o estoque",
    image_url: "https://images.unsplash.com/photo-1605523741177-cd660595c2cf?auto=format&fit=crop&w=1600&q=80",
    href: "/categoria/calcados",
    position: 2,
    active: true,
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: "c-01", name: "Marina Souza", email: "marina.souza@email.com", phone: "11988887777", orders_count: 3, total_spent_cents: 54700, created_at: "2026-06-02T10:00:00Z" },
  { id: "c-02", name: "Rafael Lima", email: "rafael.lima@email.com", phone: "11977776666", orders_count: 1, total_spent_cents: 15900, created_at: "2026-07-14T14:30:00Z" },
  { id: "c-03", name: "Camila Andrade", email: "camila.andrade@email.com", phone: "11966665555", orders_count: 2, total_spent_cents: 32800, created_at: "2026-08-01T09:15:00Z" },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "o-01",
    code: "BB00001",
    customer_name: "Marina Souza",
    customer_email: "marina.souza@email.com",
    customer_phone: "11988887777",
    shipping_address: {
      recipient: "Marina Souza",
      cep: "01310-100",
      street: "Av. Paulista",
      number: "1000",
      complement: "Apto 52",
      neighborhood: "Bela Vista",
      city: "São Paulo",
      state: "SP",
    },
    subtotal_cents: 31800,
    shipping_cents: 1990,
    total_cents: 33790,
    payment_method: "mercadopago",
    payment_status: "approved",
    mercadopago_payment_id: "mp-12345678",
    status: "enviado",
    items: [
      { id: "oi-01", order_id: "o-01", product_id: "p-01", product_name: "Vestido Jardim Encantado", variation_label: "Tamanho 2", unit_price_cents: 15900, quantity: 2 },
    ],
    created_at: "2026-09-02T15:20:00Z",
  },
  {
    id: "o-02",
    code: "BB00002",
    customer_name: "Rafael Lima",
    customer_email: "rafael.lima@email.com",
    customer_phone: "11977776666",
    shipping_address: {
      recipient: "Rafael Lima",
      cep: "04538-133",
      street: "Rua Funchal",
      number: "418",
      complement: null,
      neighborhood: "Vila Olímpia",
      city: "São Paulo",
      state: "SP",
    },
    subtotal_cents: 15900,
    shipping_cents: 1990,
    total_cents: 17890,
    payment_method: "mercadopago",
    payment_status: "pending",
    mercadopago_payment_id: null,
    status: "aguardando_pagamento",
    items: [
      { id: "oi-02", order_id: "o-02", product_id: "p-10", product_name: "Tênis Primeiros Saltos", variation_label: "Tam. 21", unit_price_cents: 15900, quantity: 1 },
    ],
    created_at: "2026-09-08T11:05:00Z",
  },
  {
    id: "o-03",
    code: "BB00003",
    customer_name: "Camila Andrade",
    customer_email: "camila.andrade@email.com",
    customer_phone: "11966665555",
    shipping_address: {
      recipient: "Camila Andrade",
      cep: "05407-002",
      street: "Rua Cardeal Arcoverde",
      number: "2020",
      complement: "Casa 2",
      neighborhood: "Pinheiros",
      city: "São Paulo",
      state: "SP",
    },
    subtotal_cents: 26600,
    shipping_cents: 0,
    total_cents: 26600,
    payment_method: "mercadopago",
    payment_status: "approved",
    mercadopago_payment_id: "mp-87654321",
    status: "entregue",
    items: [
      { id: "oi-03", order_id: "o-03", product_id: "p-13", product_name: "Laço Duplo Framboesa", variation_label: null, unit_price_cents: 3900, quantity: 2 },
      { id: "oi-04", order_id: "o-03", product_id: "p-14", product_name: "Mochila Pequena Aventureira", variation_label: null, unit_price_cents: 8900, quantity: 1 },
      { id: "oi-05", order_id: "o-03", product_id: "p-12", product_name: "Sandália Tarde de Sol", variation_label: "Tam. 24", unit_price_cents: 9900, quantity: 1 },
    ],
    created_at: "2026-08-20T09:40:00Z",
  },
];
